
table fact_codingame
    lineageTag: 174382a2-af2e-4851-8824-497d792900dc

    column codingame_key
        dataType: int64
        sourceColumn: codingame_key
        summarizeBy: none

    column date_key
        dataType: int64
        sourceColumn: date_key
        summarizeBy: none

    column user_key
        dataType: int64
        sourceColumn: user_key
        summarizeBy: none

    column framework_name
        dataType: string
        sourceColumn: framework_name
        summarizeBy: none

    column score
        dataType: double
        sourceColumn: score
        summarizeBy: sum

    column total_score
        dataType: double
        sourceColumn: total_score
        summarizeBy: sum

    column session_count
        dataType: int64
        sourceColumn: session_count
        summarizeBy: sum

    partition fact_codingame = m
        mode: import
        source =
            let
                Source = MySQL.Database(PBI_MySqlServer, PBI_MySqlDatabase),
                Data = try Source{[Schema=PBI_MySqlDatabase, Item="fact_codingame"]}[Data]
                    otherwise try Source{[Name="fact_codingame", Kind="Table"]}[Data]
                    otherwise try Source{[Item="fact_codingame"]}[Data]
                    otherwise Value.NativeQuery(Source, "SELECT * FROM fact_codingame", null),
                Typed = {
                    {"codingame_key", Int64.Type}, {"date_key", Int64.Type}, {"user_key", Int64.Type},
                    {"framework_name", type text}, {"score", type number}, {"total_score", type number},
                    {"session_count", Int64.Type}
                },
                Demo = Table.TransformColumnTypes(
                    Table.FromRecords({
                        [codingame_key = 1, date_key = 20260515, user_key = 1, framework_name = "React", score = 78, total_score = 100, session_count = 1],
                        [codingame_key = 2, date_key = 20260515, user_key = 1, framework_name = "Spring", score = 65, total_score = 100, session_count = 1],
                        [codingame_key = 3, date_key = 20260515, user_key = 1, framework_name = "Angular", score = 88, total_score = 100, session_count = 1]
                    }),
                    Typed
                ),
                Loaded = if Table.IsEmpty(Data) then Demo else Table.TransformColumnTypes(Data, Typed),
                Result = Loaded
            in
                Result
