
table fact_quiz
    lineageTag: 79b3b401-9ff4-48af-a174-0998700faf0b

    column quiz_key
        dataType: int64
        sourceColumn: quiz_key
        summarizeBy: none

    column date_key
        dataType: int64
        sourceColumn: date_key
        summarizeBy: none

    column user_key
        dataType: int64
        sourceColumn: user_key
        summarizeBy: none

    column score
        dataType: int64
        sourceColumn: score
        summarizeBy: sum

    column passed
        dataType: int64
        sourceColumn: passed
        summarizeBy: none

    column attempt_count
        dataType: int64
        sourceColumn: attempt_count
        summarizeBy: sum

    partition fact_quiz = m
        mode: import
        source =
            let
                Source = MySQL.Database(PBI_MySqlServer, PBI_MySqlDatabase),
                Data = try Source{[Schema=PBI_MySqlDatabase, Item="fact_quiz"]}[Data]
                    otherwise try Source{[Name="fact_quiz", Kind="Table"]}[Data]
                    otherwise try Source{[Item="fact_quiz"]}[Data]
                    otherwise Value.NativeQuery(Source, "SELECT * FROM fact_quiz", null),
                Typed = {
                    {"quiz_key", Int64.Type}, {"date_key", Int64.Type}, {"user_key", Int64.Type},
                    {"score", Int64.Type}, {"passed", Int64.Type}, {"attempt_count", Int64.Type}
                },
                Demo = Table.TransformColumnTypes(
                    Table.FromRecords({
                        [quiz_key = 1, date_key = 20260515, user_key = 1, score = 85, passed = 1, attempt_count = 1],
                        [quiz_key = 2, date_key = 20260515, user_key = 1, score = 60, passed = 0, attempt_count = 1],
                        [quiz_key = 3, date_key = 20260515, user_key = 1, score = 92, passed = 1, attempt_count = 1]
                    }),
                    Typed
                ),
                Loaded = if Table.IsEmpty(Data) then Demo else Table.TransformColumnTypes(Data, Typed),
                Result = Loaded
            in
                Result
